window.SITE_CONFIG = {
  "brand": {"name":"PULSO","companyName":"PULSO Recovery","logoIcon":"/assets/images/logo/logo-mark.svg","tagline":"Recovery, on your terms."},
  "contact": {"email":"hello@example.com","address":"1420 Market Street, San Francisco, CA 94102","responseTime":"We aim to reply within 1–2 business days.","phoneRequired":false},
  "product": {"id":"pulso-massage-gun","name":"PULSO Massage Gun","sku":"PULSO-MG-01","subtitle":"Professional-Grade Percussion Recovery","currency":"USD","price":199,"oldPrice":null,"stock":true,"stockText":"In stock and ships today.","batteryHours":"6+","speedCount":5,"stallForce":"Up to 60 lbs","noiseDb":"< 45 dB","showNoiseDb":true,"attachmentCount":5,"image":"/assets/images/product/product-main.jpg"},
  "speeds":[{"name":"RELAX","rpm":1800,"text":"A gentle start for daily reset."},{"name":"MELLOW","rpm":2100,"text":"Easy movement for lighter tension."},{"name":"BALANCE","rpm":2400,"text":"Everyday power for a steady routine."},{"name":"DEEP","rpm":2700,"text":"Focused intensity after demanding days."},{"name":"INTENSE","rpm":3200,"text":"Maximum setting for experienced users."}],
  "policies":{"returns":"60-Day Returns","returnsShort":"Try it. Love it.","warranty":"2-Year Warranty","warrantyShort":"Built to last.","shipping":"Fast U.S. Shipping","shippingShort":"2–4 business days"},
  "commerce":{"mode":"inquiry","localStorageKey":"pulso_cart_v1","taxEnabled":false,"cta":"REQUEST A QUOTE","paymentMethods":["VISA","MC","AMEX","DISCOVER","SHOP PAY"]},
  "bundles":[{"id":"single","sku":"PULSO-SINGLE","name":"Single Kit","quantity":1,"price":199,"oldPrice":null,"image":"/assets/images/bundles/bundle-single.jpg","features":["Massage gun","5 attachments","Carrying case","2-year warranty"]},{"id":"duo","sku":"PULSO-DUO","name":"Recovery Duo","quantity":1,"price":359,"oldPrice":398,"image":"/assets/images/bundles/bundle-duo.jpg","popular":true,"features":["2 massage guns","2 attachment sets","2 carrying cases","2-year warranty each"]},{"id":"complete","sku":"PULSO-COMPLETE","name":"Complete Bundle","quantity":1,"price":229,"oldPrice":267,"image":"/assets/images/bundles/bundle-complete.jpg","features":["Massage gun","5 attachments","Charging kit","Premium carrying case"]}],
  "reviews":{"rating":null,"count":null,"recommendationRate":null,"distribution":null,"items":[{"name":"Michael T.","stars":5,"title":"A smarter post-training routine.","text":"Easy to control, solid in the hand, and simple to bring to the gym. The speed range makes it useful throughout my week."},{"name":"Sarah L.","stars":5,"title":"Quiet, compact, and capable.","text":"The attachments make it easy to adapt the experience. The case stays in my work bag, so it is ready when I need it."},{"name":"David R.","stars":5,"title":"Built for regular use.","text":"The controls are clear, battery life is excellent, and the balanced grip feels considered."}]},
  "certifications":[],
  "offer":{"enabled":true,"oldPrice":199,"price":149,"discountLabel":"25% OFF","endsAt":"2027-12-31T23:59:59-08:00","expiredBehavior":"message","expiredMessage":"OFFER ENDED"},
  "shippingZones":{"US":{"label":"United States","rate":0,"freeLabel":"FREE"},"CA":{"label":"Canada","rate":18},"EU":{"label":"European Union","rate":24},"default":{"label":"Other regions","rate":null}},
  "navigation":[{"label":"SHOP","href":"/product-pages/shop.html"},{"label":"THE TECH","href":"/#engineering"},{"label":"IN ACTION","href":"/product-pages/see-it-in-action.html"},{"label":"RESULTS","href":"/product-pages/reviews.html"},{"label":"SUPPORT","href":"/contact/"}],
  "socialLinks":{"instagram":"#","youtube":"#","tiktok":"#"},
  "advertise":{"title":"Advertise & Collaborate","text":"We are always open to new opportunities, high-impact collaborations, and tailored business partnerships. Whether you want to advertise your brand to our audience, launch a joint project, or book our professional services, we are ready to bring your ideas to life. Every business is unique, and we don't believe in one-size-fits-all solutions. Please reach out to us using the contact form below, tell us a bit about your goals, and our team will get back to you with an exclusive, custom-tailored proposal designed strictly for your budget and objectives. Let’s build something great together."},
  "legal":{"companyLegalName":"PULSO Recovery LLC","effectiveDate":"August 9, 2026","shippingRegions":"United States, Canada, and selected international regions","consentKey":"pulso_legal_consent_v1"},
  "footer":{"message":"Portable percussion, thoughtfully engineered for the way real life moves.","copyrightText":"All rights reserved."}
};
